---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actionspanel
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: actionspanel
  template:
    metadata:
      labels:
        app: actionspanel
    spec:
      containers:
        - name: actionspanel
          image: phunki/actionspanel
          envFrom:
            - configMapRef:
                name: actionspanel
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: health
          livenessProbe:
            exec:
              command:
                - /go/bin/actionspanel
                - live
