---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actionspanel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actionspanel
  template:
    metadata:
      labels:
        app: actionspanel
    spec:
      containers:
        - name: actionspanel
          image: phunki/actionspanel
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
