---
apiVersion: v1
kind: Service
metadata:
  name: actionspanel
spec:
  selector:
    app: actionspanel
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: health
      protocol: TCP
      name: health
  type: ClusterIP
