---
apiVersion: v1
kind: Service
metadata:
  name: actionspanel
spec:
  selector:
    app: actionspanel
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  type: ClusterIP
