apiVersion: skaffold/v2beta2
kind: Config
build:
  artifacts:
    - image: phunki/actionspanel
      context: .
deploy:
  kubectl:
    manifests:
      - ./hack/local-k8s-manifests/*
portForward:
  - resourceType: service
    resourceName: actionspanel
    port: 8080
    localPort: 8080
