name: Run golangci
on: [pull_request]

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          golangci_lint_flags: "--enable-all --exclude-use-default=false"
